services:
    phpbbstudio.tcs.listener:
        class: phpbbstudio\tcs\event\setup_listener
        arguments:
            - '@auth'
            - '@dbal.conn'
            - '@language'
            - '@request'
            - '@template'
            - '@phpbbstudio.tcs.functions.common'
        tags:
            - { name: event.listener }

    phpbbstudio.tcs.functions.common:
        class: \phpbbstudio\tcs\core\functions_common
        arguments:
            - '@auth'
            - '@dbal.conn'
            - '@template'
